name: Bug Report
description: Create a report to help us improve
title: 'Bug: '
labels: bug

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Please provide a brief description of the issue you encountered.
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: Please paste the complete error message here.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version Information
      description: Please paste the output of `import histcite; histcite.show_versions()`.
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Data Source Used
      multiple: false
      options:
        - Web of Science
        - Scopus
        - CSSCI
    validations:
      required: true

  - type: textarea
    id: dataset
    attributes:
      label: Dataset Used
      description: Please upload a dataset that can reproduce the bug.
    validations:
      required: false
