name: Feature Request
description: Suggest an idea for this project
title: 'Feature: '
labels: enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Select Data Source 
      options:
        - Web of Science
        - Scopus
        - CSSCI
    validations:
      required: false
